FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install
RUN npm i -g @nestjs/cli

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start the application in development mode with hot reload
CMD ["npm", "run", "start:dev"]
