import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document, Schema as MongooseSchema } from "mongoose";
import { Types } from "mongoose";

@Schema()
export class User extends Document {
  // Unique identifier (_id is auto-generated by MongoDB)
  @Prop({ required: true, trim: true, maxlength: 64, unique: true })
  username: string;

  @Prop({
    required: true,
    trim: true,
    lowercase: true,
    unique: true,
    match: /.+\@.+\..+/,
  })
  email: string;

  @Prop({ required: true, select: false }) // Do not return by default
  passwordHash: string;

  @Prop({
    enum: ["Landlord", "Tenant", "Contractor", "Admin"],
    required: true,
    default: "Tenant",
  })
  role: string;

  @Prop({ trim: true })
  phone: string;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: "Organization" })
  organization: Types.ObjectId;

  @Prop({ default: true })
  isActive: boolean;

  @Prop({ default: Date.now, immutable: true })
  createdAt: Date;

  @Prop({ default: Date.now })
  updatedAt: Date;

  // Optional: For tenants, link to their current unit
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: "Unit" })
  unit: Types.ObjectId;

  // Optional: For landlords, link to their properties
  @Prop({ type: [{ type: MongooseSchema.Types.ObjectId, ref: "Property" }] })
  properties: Types.ObjectId[];
}

export const UserSchema = SchemaFactory.createForClass(User);
